name: 'QA check with pkgcheck'
on: [push, pull_request]
jobs:
    repoman:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: rafspiny/pkgcheck-action@1.0.2
              with:
                args: --config=.pkgcheck.conf
