name: 'QA check with pkgcheck'
on: [push, pull_request]
jobs:
    repoman:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: rafspiny/pkgcheck-action@v1.0.1
              with:
                args: --config=.pkgcheck.conf
